# Fly.io configuration file

app = "cc3d-simsurrogate"  # Change this to your preferred name
primary_region = "iad"      # Change to your preferred region (iad = Virginia)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Health check configuration
  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

# VM configuration
[[vm]]
  memory = '1gb'      # 1GB RAM (increase if needed)
  cpu_kind = 'shared'
  cpus = 1
